# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    images_directory: '%kernel.project_dir%/public/uploads/images'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\MessageHandler\IndexPostHandler:
        arguments:
            # Ասում ենք Symfony-ին. $postPersister արգումենտի համար օգտագործիր
            # կոնկրետ 'fos_elastica.object_persister.posts' service-ը։
            $postPersister: '@fos_elastica.object_persister.posts'
            # $postRepository-ն ավտոմատ կգտնվի (autowired)

        # 2. Կանխարգելիչ ուղղում PostSearchService-ի համար
    App\Service\PostSearchService:
        arguments:
            # Ասում ենք Symfony-ին. $postFinder արգումենտի համար օգտագործիր
            # կոնկրետ 'fos_elastica.finder.posts' service-ը։
            $postFinder: '@fos_elastica.finder.posts'
